version: 1.0.0

services:
  app-db:
    build: ./app-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
  auth-db:
    build: ./auth-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
  authentication:
    build: ./docker/authentication
    ports:
      - 8080:8080
    depends_on:
      - auth-db
  application:
    build: ./docker/application
    ports:
      - 8081:8081
    depends_on:
      - authentication
      - app-db